'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PKSMScriptMaker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #!/usr/bin/env python3
        '''import shlex, PKSMScript, sys, glob, shutil, os
        '''
        '''games = [&quot;PSM&quot;]
        '''
        '''def main(args):
        '''	shutil.rmtree(&quot;output&quot;, True)
        '''	os.mkdir(&quot;output&quot;)
        '''	for game in games:
        '''		generate(game)
        '''		
        '''		scriptFiles = glob.glob(&quot;*.pksm&quot;)
        '''		for pksmFile in scriptFiles:
        '''			shutil.move(pksmFile,&quot;output&quot;)
        '''	os.remove(&quot;scriptsPSM.txt&quot;)	
        '''	os.remove(&quot;PKSMScript.py&quot;)
        '''	os.remove(&quot;genScripts.py&quot;)
        '''	shutil.rmtree(&quot;__pycache__&quot;, True)
        '''	
        '''
        '''def generate(game):
        '''	with open(os.path.join(&quot;scripts%s.txt&quot; % game)) as pksmArgFile:
        '''		for [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property genScripts() As String
            Get
                Return ResourceManager.GetString("genScripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #!/usr/bin/python3
        '''import argparse
        '''
        '''
        '''# PKSM script structure
        '''# u8 magic[10]        // PKSMSCRIPT
        '''# u32 offset          // save offset to write the data to
        '''# u32 length          // payload length
        '''# u8 payload[len]     // payload data
        '''# u32 repeat_times    // repeat payload n times
        '''# ...
        ''' 
        ''' 
        '''parser = argparse.ArgumentParser(description = &apos;Creates .pksm script files&apos;)
        '''parser.add_argument(&apos;output&apos;, help = &apos;Output file name&apos;)
        '''parser.add_argument(&apos;-i&apos;, action = &apos;append&apos;, nargs = 4, metavar = (&apos;ofs&apos;, &apos;len&apos;, &apos;pld&apos;, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PKSMScript() As String
            Get
                Return ResourceManager.GetString("PKSMScript", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
